// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Api.Data.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e8e95630-e4c8-439c-9271-8f4feb7724c5"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var customer = CustomerEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var sale = SaleEntityType.Create(this);
            var saleItem = SaleItemEntityType.Create(this);

            SaleItemEntityType.CreateForeignKey1(saleItem, product);
            SaleItemEntityType.CreateForeignKey2(saleItem, sale);

            CustomerEntityType.CreateAnnotations(customer);
            ProductEntityType.CreateAnnotations(product);
            SaleEntityType.CreateAnnotations(sale);
            SaleItemEntityType.CreateAnnotations(saleItem);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.3");
            AddAnnotation("Relational:DefaultSchema", "shop");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
